[workspace]
resolver = "2"
members = ["day*", "common", "util"]

[workspace.dependencies]
anyhow = "1.0.75"
counter = "0.5.7"
itertools = "0.11.0"
nom = "7.1.3"
rand = "0.8.5"
rayon = "1.8.0"
regex = "1.10.2"

[profile.release]
debug = true
